[package]
name = "aria"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "1.0"
ariadne = "0.4"
logos = "0.14"
codespan-reporting = "0.11"
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.4"
